<?php

// Misc Language Pack for Discuz! Version 1.0.0
// Translated by Crossday

$language = array
(
	'discuz_lang' => 'misc',

	'anonymous' => '匿名',

	'post_hidden' => '**** 本内容被作者隐藏 *****',
	'post_banned' => '*** 作者被禁止或删除 内容自动屏蔽 ***',
	'post_single_banned' => '*** 该帖被屏蔽 ***',
	'post_reply_quote' => '原帖由 $thaquote[author] 于 $time 发表',
	'post_edit' => '\n\n[[i] 本帖最后由 $editor 于 $edittime 编辑 [/i]]',
	'post_edit_regexp' => '/\n{2}\[\[i\] 本帖最后由 .*? 于 .*? 编辑 \[\/i\]\]$/s',

	'price' => '售价',
	'pay_view' => '记录',
	'attachment_buy' => '购买',

	'post_trade_yuan' => '元',
	'post_trade_seller' => '卖家',
	'post_trade_name' => '商品名称',
	'post_trade_costprice' => '商品原价',
	'post_trade_price' => '商品价格',
	'post_trade_quality' => '商品成色',
	'post_trade_locus' => '商品所在地',
	'post_trade_transport_type' => '物流方式',
	'post_trade_transport_seller' => '卖家承担运费',
	'post_trade_transport_buyer' => '买家承担运费',
	'post_trade_transport_mail' => '平邮',
	'post_trade_transport_express' => '快递',
	'post_trade_transport_virtual' => '虚拟物品或无需邮递',
	'post_trade_transport_physical' => '买家收到货物后直接支付给物流公司',
	'post_trade_locus' => '所在地点',
	'post_trade_description' => '商品描述',
	'post_trade_pm_subject' => '[议价]',
	'post_trade_pm_buynum' => '购买数量',
	'post_trade_pm_wishprice' => '我期望的价格是',
	'post_trade_pm_reason' => '我议价的理由是',
	'payment_unit' => '元',

	'attach' => '附件',
	'attach_pay' => '收费附件',
	'attach_credits_policy' => '查看积分策略说明',
	'attach_img' => '图片附件',
	'attach_readperm' => '阅读权限',
	'attach_img_zoom' => '点击在新窗口查看全图\\nCTRL+鼠标滚轮放大或缩小',
	'attach_img_thumb' => '点击在新窗口查看全图',
	'attach_downloads' => '下载次数',

	'supe_dateline' => '时间',
	'supe_download_count' => '下载次数',
	'supe_picture_story' => '图片故事',
	'supe_software_size' => '软件大小',
	'supe_software_version' => '软件版本',
	'supe_software_producer' => '开  发  商',
	'supe_software_downfrom' => '下载来源',
	'supe_software_language' => '软件语言',
	'supe_software_permission' => '授权方式',
	'supe_software_system' => '运行平台',
	'supe_digest_0' => '普通',
	'supe_digest_1' => '精华I',
	'supe_digest_2' => '精华II',
	'supe_digest_3' => '精华III',
	'supe_digest_level' => '精华级别',
	'supe_viewnum' => '查看次数',
	'supe_software_introduce' => '软件介绍',
	'supe_download_from_remote' => '远程下载',
	'supe_donwload_from_local' => '本地下载',
	'supe_viewnum' => '查看次数',
	'supe_snapshot' => '网页快照',
	'supe_viewsnapshot' => '查看快照',
	'supe_urldescription' => '书签介绍',
	'supe_linkurl' => '地址',

	'post_trade_transport' => '邮费',
	'post_trade_transport_mail' => '平邮',
	'post_trade_quality' => '商品成色',
	'post_trade_quality_new' => '全新',
	'post_trade_quality_secondhand' => '二手',

	'trade_unstart' => '<font color="gray">未生效的交易</font>',
	'trade_waitbuyerpay' => '等待买家付款',
	'trade_waitsellerconfirm' => '交易已创建，等待卖家确认',
	'trade_sysconfirmpay' => '确认买家付款中，暂勿发货',
	'trade_waitsellersend' => '买家已付款，等待卖家发货',
	'trade_waitbuyerconfirm' => '卖家已发货，买家确认中',
	'trade_syspayseller' => '买家确认收到货，等待支付宝打款给卖家',
	'trade_finished' => '<font color="green">交易成功结束</font>',
	'trade_closed' => '<font color="gray">交易中途关闭（未完成）</font>',
	'trade_waitselleragree'  => '等待卖家同意退款',
	'trade_sellerrefusebuyer' => '卖家拒绝买家条件，等待买家修改条件',
	'trade_waitbuyerreturn' => '卖家同意退款，等待买家退货',
	'trade_waitsellerconfirmgoods' => '等待卖家收货',
	'trade_waitalipayrefund' => '双方已经一致，等待支付宝退款',
	'trade_alipaycheck' => '支付宝处理中',
	'trade_overedrefund' => '结束的退款',
	'trade_refundsuccess' => '<font color="green">退款成功</font>',
	'trade_refundclosed' => '<font color="green">退款关闭</font>',

	'trade_offline_1' => '交易单生效',
	'trade_offline_4' => '我已付款，等待卖家发货',
	'trade_offline_5' => '我已发货',
	'trade_offline_7' => '我收到货，交易成功结束',
	'trade_offline_8' => '取消此次交易',
	'trade_offline_10' => '我要退货，等待卖家同意退款',
	'trade_offline_11' => '卖家拒绝退款',
	'trade_offline_12' => '卖家同意退款',
	'trade_offline_13' => '我已退货，等待卖家收货',
	'trade_offline_17' => '卖家收到退货，已退款',

	'trade_message_4' => '可输入付款方式、银行账号等信息',
	'trade_message_5' => '可输入发货公司、发货单号等信息',
	'trade_message_13' => '可输入发货公司、发货单号等信息',

	'credit_payment' => '积分充值',
	'credit_forum_payment' => '论坛积分充值',

	'formulaperm_digestposts' => '精华帖数',
	'formulaperm_posts' => '发帖数',
	'formulaperm_oltime' => '在线时间(小时)',
	'formulaperm_pageviews' => '页面浏览量',
	'formulaperm_and' => '并且',
	'formulaperm_or' => '或者',
	'formulaperm_extcredits' => '自定义积分',

	'login_normal_mode' => '正常模式',
	'login_switch_invisible_mode' => '切换到隐身模式',
	'login_switch_normal_mode' => '切换到正常模式',
	'login_invisible_mode' => '隐身模式',

	'eccredit_explain' => '解释',

	'google_site_0' => '网页搜索',
	'google_site_1' => '站内搜索',
	'google_sa' => '搜索'
);

?>